events integ tests
klothoplatform/sample-apps pull request #42
Opened 2022-10-24 15:03 UTC by jhsinger-klotho

events integ test and policy pack

also added persist and another get endpoint to test if our pubsub is truly working. Before the pubsub didnt write anything anywhere so tests would always pass if the initial lambda got a response

2022-10-25 00:24 UTC, ewucc requested changes

2022-10-25 00:24 UTC, ewucc commented on ts-events/README.md
> +<<<<<<< HEAD
looks like some merge stuff got left in

2022-10-25 00:24 UTC, ewucc commented on ts-events/README.md
> +=======
same ^

2022-10-25 00:24 UTC, ewucc commented on ts-events/README.md
> +>>>>>>> 0e6baf0 (placeholder)
same ^

2022-10-25 00:24 UTC, ewucc commented on ts-events/test/happy_path.test.ts
> +const testUser = "user"
rip timmy the test user

2022-10-26 21:32 UTC, yuval-klotho commented on ts-events/test/pulumi/index.ts
> +        const lambda = lambdas[0].asType(aws.lambda.Function)!;
Should we test all of them (not just the first one)?

2022-10-26 21:52 UTC, ewucc approved these changes
Yuval had an open comment but i think it's non blocking for now

2022-10-26 22:18 UTC, merged